server:
  port: 8080



spring:
  application:
    name: job.ts.v2
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/jobts_v2?authSource=admin
  servlet:
    multipart:
      enabled:true
      max-file-size:50MB
      max-request-size:100MB


logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

jwt:
  secret: "QWx3YXlzLXNlY3VyZS1hbmQtc3Ryb25nLWtleS1mb3Itam90LTUxMi1zZWN1cml0eS0xMjM0NTY3ODkwMTIzNDU2Nzg5"
  expiredDay: 86400000
