server:
  port: ${SERVER_PORT}



spring:
  application:
    name: job.ts.v2
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/demo
#      database: demo
  servlet:
    multipart:
      enabled:true
      max-file-size:50MB
      max-request-size:100MB



logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiredDay: 86400000
